source 'https://rubygems.org'

if File.exist? File.expand_path('../../commons', __FILE__)
  gem 'boxes-commons', path: '../commons'
else
  gem 'boxes-commons', '= 1.0.0'
end

gem 'rmagick', github: 'gemhome/rmagick'

group :dev do
  gem 'boxes-test', path: '../test'

  gem 'bundler', '~> 1.6'
  gem 'rake'
  gem 'rspec', '~> 3.1.0'
  gem 'cucumber', '~> 1.3.17'
end