$:.unshift File.expand_path('../lib', __FILE__)
require 'bundler/setup'
require 'rake/clean'
require 'rspec/core/rake_task'
require 'cucumber'
require 'cucumber/rake/task'
require 'boxes/version'
require 'clerk/version'

RSpec::Core::RakeTask.new :spec do |t|
  t.rspec_opts = ['--color', '--format progress']
end

Cucumber::Rake::Task.new(:features) do |t|
  t.cucumber_opts = 'features --format pretty'
end
task :default => [:spec, :features]

namespace :docker do
  commons_gem = "../commons/boxes-commons-#{Boxes::VERSION}.gem"
  file commons_gem do
    sh "cd ../commons/; #{$0} gem"
  end
  CLEAN << commons_gem

  directory 'pkg'
  CLEAN << 'pkg'

  file 'pkg/boxes-commons.gem' => ['pkg', commons_gem] do
    sh "cp #{commons_gem} pkg/boxes-commons.gem"
  end

  desc 'Build docker image'
  task :build => 'pkg/boxes-commons.gem' do
    sh "docker build -t boxes/clerk:#{Clerk::VERSION} ."
    sh "docker tag boxes/clerk:#{Clerk::VERSION} boxes/clerk:latest"
  end
end