$:.unshift File.expand_path('../lib', __FILE__)
require 'bundler/setup'
require 'rspec/core/rake_task'
require 'boxes/version'

RSpec::Core::RakeTask.new :spec do |t|
  t.rspec_opts = ['--color', '--format progress']
end
task :default => :spec

sources = FileList['bin/**/*', 'lib/**/*', 'spec/**/*', '*.gemspec']
gem = "boxes-commons-#{Boxes::VERSION}.gem"
file gem => sources do
  sh 'gem build boxes-commons.gemspec'
end

desc 'Build gem file'
task :gem => gem