source 'https://rubygems.org'

if File.exist? File.expand_path('../../commons', __FILE__)
  gem 'boxes-commons', path: '../commons'
else
  gem 'boxes-commons', '= 1.0.0'
end

gem 'grape', '~> 0.9.0'
gem 'jerry', '~> 1.0.1'

group :dev do
  if File.exist? File.expand_path('../../test', __FILE__)
    gem 'boxes-test', '= 0.0.1', path: '../test'
  end

  gem 'bundler', '~> 1.6'
  gem 'rake'
  gem 'rspec', '~> 3.1.0'
  gem 'thin', '~> 1.6.3'
  gem 'rack-test', '~> 0.6.2'
end